builds:
  - binary: chatgptdash
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env: 
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release: 
  prerelease: auto 

universal_binaries:
  - replace: true

brews: 
 - name: chatgptdash
   homepage: https://github.com/dash2701/chatgptdash
   tap: 
     owner: dash2701
     name: homebrew-dash2701
   commit_author:
     name: dash2701
     email: amitdash8811@gmail.com

checksum:
  name_template: 'checksums.txt'